### ISSUE TITLE
感觉说的不全,是不是遗漏很多功能?

### ISSUE THREAD

**Issue by wlzzqkrs** [ShawyerPeng/BitsIM#1]
感觉说的不全/

**Comment by ShawyerPeng** [comment]
@wlzzqkrs 抱歉，我也是正在学习 IM 开发中，README 中描述的功能只是最终想实现完成的，还有很多乱七八糟的笔记也是写在上面的，目前还只实现了基本的通讯功能。现在已将 README 移除，以免误导大家。
